### ISSUE TITLE
Refactoring/Improvements

### ISSUE THREAD

**Issue by sangloo** [Togal-ai-Team/eslint-config-togal#10]
- New Global image cache (currently not working properly due to CORS)
- Rewriting the API layer in the editor (smart pagination, cleaner code, avoid multiple calls)
- Refactoring the Header component (+ new Header design)

**Comment by shoniko** [comment]
- CORS issue is on pause. It appears on all thumbnails, not for original images. Needs a separate ticket to find a correct setup for both Frontend and Backend. @shoniko to create an issue.
- Rewriting the API layer  - in progress
- Refactoring the Header component - no started yet.

**Comment by shoniko** [comment]
Rewriting the API layer - done.
Refactoring the Header component - in progress.

**Comment by shoniko** [comment]
Should be up on Monday (in shared-frontend and used by Frontend)

**Comment by shoniko** [comment]
Need to add printing and legend to refactored Canvas. See review here: https://www.loom.com/share/1ee0f0ce631441d58296cd3542525a7b

**Comment by shoniko** [comment]
This is done!
