### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by sangloo** [Togal-ai-Team/eslint-config-togal#15]

**Comment by sangloo** [comment]
https://www.loom.com/share/c64965dcc64b48c798508ce27d4a6f17 : when I select a polygon from the quantity panel and try to copy-paste it , the page turns blank

**Comment by sangloo** [comment]
Dimension line bug

**Comment by sangloo** [comment]
Labeler header disappearing

**Comment by sangloo** [comment]
Image loading issue (cache)

**Comment by JenniferNassar** [comment]
https://www.loom.com/share/71f5a177916c4a299b10deaecbc05c53 : one more time, the split tool is not working

**Comment by JenniferNassar** [comment]
after I rotated the drawing and I tried to togal it ... this is what happens : ![Screenshot 2022-02-11 174058.png](https://images.zenhubusercontent.com/613759988f7574c839cb86e7/30ae4222-f570-481d-8bd6-804ace74d7a8)

**Comment by shoniko** [comment]
@JenniferNassar can you please test the split tool fix?
The rotation bug still to be fixed.

**Comment by JenniferNassar** [comment]
https://www.loom.com/share/2bb6202df15e401ba0787057ba7da62f: I can select a markup tool and a normal shape(rectangle and polygon) at the same time

**Comment by JenniferNassar** [comment]
https://www.loom.com/share/a067f055ecaf40c8b90cad022f461fde : this is a video for the rotation and togaling bug with the console

**Comment by shoniko** [comment]
The URL of the image changes after Togaling and that breaks the current cache change. Need to fix.
