### ISSUE TITLE
bugs2

### ISSUE THREAD

**Issue by sangloo** [Togal-ai-Team/eslint-config-togal#17]
Adding new found bugs here

**Comment by sangloo** [comment]
add delete check for classifications.....

**Comment by JenniferNassar** [comment]
https://www.loom.com/share/2bb6202df15e401ba0787057ba7da62f: I can select a markup tool and a normal shape(rectangle and polygon) at the same time

**Comment by sangloo** [comment]
Clean data of duplicated items
