### ISSUE TITLE
user Video feedback

### ISSUE THREAD

**Issue by sangloo** [Togal-ai-Team/eslint-config-togal#18]
- Orthoganl line
- ON polygon, add option to snap to first point deg ....

**Comment by Togal-ai** [comment]
https://togal-ai.slack.com/files/U01PA1Y7YGP/F0347AN7P2A/image_from_ios.mov

**Comment by Togal-ai** [comment]
https://togal-ai.slack.com/files/U01PA1Y7YGP/F0347ANMS5C/image_from_ios.mov

**Comment by shoniko** [comment]
This is an old issue and it is actually already done 🤷‍♂️
