### ISSUE TITLE
Get fatal error when navigate to adjacent drawing from a drawing that is Togaling

### ISSUE THREAD

**Issue by cpettibone** [Togal-ai-Team/eslint-config-togal#31]
I was Togaling a drawing While it was still processing, I navigated to an adjacent drawing so I could launch Togaling of that one. I got this error. I had recently uploaded the drawings, so it's possible Drawing 2 was finished processing the upload. Doesn't matter though, we shouldn't show this error. 

![Screen Shot 2023-01-05 at 4.35.51 PM.png](https://images.zenhubusercontent.com/618ea88b279f67f605afd309/f9a3e60c-4871-4e4a-9abd-446dee55c4dd)

**Comment by shoniko** [comment]
@yuliiabilan please test this

**Comment by yuliiabilan** [comment]
no error appearing both on STG and Prod

https://images.zenhubusercontent.com/371805189/b897d6ed-210c-4ae6-9219-2e1ae93178fa/31_ok__1_.mp4
